version: '4.28.0'
services:
  db:
    image: mysql:8.0.25
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - myapp_data:/var/lib/mysql

volumes:
  myapp_data: